on:
  push:
    paths:
      "*"
jobs:
  my_first_job:
    runs-on: bioconductor/bioconductor_full:devel
    steps:
      - uses: actions/checkout@master
      - name: My first step
        uses: seandavi/bioc_actions/check@master
